version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x64
 
configuration:
  - Release

init:
  - set PATH=C:\Qt\5.11.1\msvc2017_64;%PATH%

install:
    - git submodule update --init --recursive

before_build:
    - mkdir build
    - cd build
    - cmake -G "Visual Studio 15 2017 Win64" -DIVW_PACKAGE_PROJECT=ON -DIVW_PACKAGE_INSTALLER=ON -DIVW_MODULE_VECTORFIELDVISUALIZATION=OFF -DIVW_MODULE_VECTORFIELDVISUALIZATIONGL=OFF ..
    - cmake -G "Visual Studio 15 2017 Win64" -DIVW_PACKAGE_PROJECT=ON -DIVW_PACKAGE_INSTALLER=ON -DIVW_MODULE_VECTORFIELDVISUALIZATION=OFF -DIVW_MODULE_VECTORFIELDVISUALIZATIONGL=OFF ..

build:
  parallel: true
  project: $(APPVEYOR_BUILD_FOLDER)\build\PACKAGE.vcxproj